seed: 42

data:
  dataset: rwf2000
  data_root: "/scratch/saichava/data/RWF-2000"
  num_frames: 16
  img_size: 224
  batch_size: 8
  num_workers: 4
  mean: [0.45, 0.45, 0.45]
  std: [0.225, 0.225, 0.225]
  flip_prob: 0.5

model:
  name: r3d18
  pretrained: true
  num_classes: 2

train:
  epochs: 8
  lr: 0.0001
  weight_decay: 0.0001
  device: "cuda"
  log_interval: 10

eval:
  device: "cuda"
